from typing import Protocol

from app.contracts import Project


class ProjectRepository(Protocol):
    def create(self, project: Project) -> Project: ...
    def get(self, project_id: str, *, lightweight: bool = False) -> Project: ...
    def list(self, *, lightweight: bool = False) -> list[Project]: ...
    def save(self, project: Project, *, source: bytes | bytearray | None = None) -> Project: ...
    def save_many(self, projects: list[Project]) -> list[Project]: ...
    def delete(self, project_id: str, *, expected_version: int | None = None) -> None: ...
    def save_source(self, project_id: str, content: bytes | bytearray) -> None: ...
    def get_source(self, project_id: str) -> bytes | None: ...
    def save_export(self, project_id: str, artifact_id: str, content: bytes) -> None: ...
    def publish_export(self, project: Project, artifact_id: str, content: bytes) -> Project: ...
    def get_export(self, project_id: str, artifact_id: str) -> bytes | None: ...
