import type { ComponentProps } from 'react';
import type {
  AutonomousRunController,
  AutonomousRunOptions,
} from '@/features/assistant/model/autonomous/useAutonomousRunController';
import type { RunStatus } from './RunStatus';
import type { RunApproval } from './RunApproval';
import type { RunComposer } from './RunComposer';
import type { RunHistory } from './RunHistory';
import type { RunTask } from './RunTask';
import type { PlacementResult } from './PlacementResult';
import type { ExistingResult } from './ExistingResult';
import type { ReadResults } from './ReadResults';
import type { RunQuestion } from './RunQuestion';
import type { RunActivity } from './RunActivity';
import type { RunFeedback } from './RunFeedback';

/** Bind the controller to concrete view contracts without exposing its other operations. */
export function getAutonomousPanelView(
  controller: AutonomousRunController,
  options: Pick<AutonomousRunOptions, 'projectId' | 'onPreviewChange'>,
) {
  return {
    status: {
      lifecycle: controller.lifecycle,
      creating: controller.creating,
      restoring: controller.restoring,
      failedRestore: controller.failedRestore,
      run: controller.run,
      reviewStatus: controller.reviewStatus,
      incomplete: controller.incomplete,
      committed: controller.committed,
      result: controller.result,
    } satisfies ComponentProps<typeof RunStatus>,
    actions: {
      approval: {
        approval: controller.approval,
        run: controller.run,
        zoneChange: controller.zoneChange,
        existing: controller.existing,
        zoneRequested: controller.zoneRequested,
        result: controller.result,
        previewState: controller.previewState,
        busy: controller.busy,
        decisionDisabled: controller.decisionDisabled,
        retry: controller.retry,
        zonePreview: controller.zonePreview,
        previewUnavailable: controller.previewUnavailable,
        approve: controller.approve,
        stopping: controller.stopping,
        cancel: controller.cancel,
        onPreviewChange: options.onPreviewChange,
      } satisfies ComponentProps<typeof RunApproval>,
      composer: {
        approval: controller.approval,
        submit: controller.submit,
        creating: controller.creating,
        currentSelection: controller.currentSelection,
        submitted: controller.submitted,
        busy: controller.busy,
        availableSelectionLabel: controller.availableSelectionLabel,
        answering: controller.answering,
        inputRef: controller.inputRef,
        draft: controller.draft,
        setDraft: controller.setDraft,
        inputDisabled: controller.inputDisabled,
        restoring: controller.restoring,
        lifecycle: controller.lifecycle,
        active: controller.active,
      } satisfies ComponentProps<typeof RunComposer>,
    },
    content: {
      history: {
        historyOpen: controller.historyOpen,
        setHistoryOpen: controller.setHistoryOpen,
        runs: controller.runs,
        runId: controller.runId,
        decisionDisabled: controller.decisionDisabled,
        openRun: controller.openRun,
        projectId: options.projectId,
      } satisfies ComponentProps<typeof RunHistory>,
      task: {
        failedRestore: controller.failedRestore,
        restoring: controller.restoring,
        decisionDisabled: controller.decisionDisabled,
        retryRestore: controller.retryRestore,
        run: controller.run,
        creating: controller.creating,
        fillDraft: controller.fillDraft,
        active: controller.active,
        result: controller.result,
        existing: controller.existing,
        issues: controller.issues,
        shortlist: controller.shortlist,
        status: controller.status,
        acceptedSelectionLabel: controller.acceptedSelectionLabel,
        draft: controller.draft,
        submitted: controller.submitted,
        lifecycle: controller.lifecycle,
        busy: controller.busy,
        continueRun: controller.continueRun,
        stopping: controller.stopping,
        canCancel: controller.canCancel,
        cancel: controller.cancel,
      } satisfies ComponentProps<typeof RunTask>,
      placement: {
        result: controller.result,
        reviewStatus: controller.reviewStatus,
        reviewNotice: controller.reviewNotice,
        scopeLabels: controller.scopeLabels,
        zones: controller.zones,
        speciesIds: controller.speciesIds,
        speciesNames: controller.speciesNames,
        catalog: controller.catalog,
        arrangementLabel: controller.arrangementLabel,
        kinds: controller.kinds,
        incomplete: controller.incomplete,
        run: controller.run,
        committed: controller.committed,
        approval: controller.approval,
        recoveryPending: controller.recoveryPending,
        outcomeUnknown: controller.outcomeUnknown,
        inputDisabled: controller.inputDisabled,
        fillDraft: controller.fillDraft,
        answering: controller.answering,
      } satisfies ComponentProps<typeof PlacementResult>,
      existing: {
        existing: controller.existing,
        reviewStatus: controller.reviewStatus,
        committed: controller.committed,
        reviewNotice: controller.reviewNotice,
        existingScope: controller.existingScope,
        existingSpecies: controller.existingSpecies,
        previousSpecies: controller.previousSpecies,
      } satisfies ComponentProps<typeof ExistingResult>,
      read: {
        shortlist: controller.shortlist,
        project: controller.project,
        issues: controller.issues,
      } satisfies ComponentProps<typeof ReadResults>,
      question: {
        answering: controller.answering,
        run: controller.run,
        incomplete: controller.incomplete,
        staleSelection: controller.staleSelection,
        selectionRecovery: controller.selectionRecovery,
        decisionDisabled: controller.decisionDisabled,
        remediesForSelection: controller.remediesForSelection,
        inputDisabled: controller.inputDisabled,
        fillDraft: controller.fillDraft,
      } satisfies ComponentProps<typeof RunQuestion>,
      activity: {
        events: controller.events,
        incomplete: controller.incomplete,
      } satisfies ComponentProps<typeof RunActivity>,
      feedback: {
        stale: controller.stale,
        retryBlocked: controller.retryBlocked,
        busy: controller.busy,
        decisionDisabled: controller.decisionDisabled,
        retry: controller.retry,
        existingUnverified: controller.existingUnverified,
        zoneBlocked: controller.zoneBlocked,
        run: controller.run,
        status: controller.status,
        committed: controller.committed,
        shownZone: controller.shownZone,
        zoneCommitted: controller.zoneCommitted,
        mapControl: controller.mapControl,
        error: controller.error,
        failureRemedy: controller.failureRemedy,
        recoveryPending: controller.recoveryPending,
        outcomeUnknown: controller.outcomeUnknown,
        refreshOutcome: controller.refreshOutcome,
        canCancel: controller.canCancel,
        active: controller.active,
        approval: controller.approval,
        stopping: controller.stopping,
        cancel: controller.cancel,
      } satisfies ComponentProps<typeof RunFeedback>,
      zonePreview: controller.stale ? null : controller.zonePreview,
      appliedZoneChange: controller.appliedZoneChange,
    },
  };
}
export type AutonomousPanelView = ReturnType<typeof getAutonomousPanelView>;
