from typing import Protocol

from app.operations.contracts import OperationKind, ProjectOperation


class OperationRepository(Protocol):
    def create(self, operation: ProjectOperation) -> ProjectOperation: ...
    def get(self, operation_id: str) -> ProjectOperation: ...
    def save(self, operation: ProjectOperation) -> ProjectOperation: ...
    def compare_and_save(
        self, expected: ProjectOperation, operation: ProjectOperation
    ) -> ProjectOperation | None: ...
    def get_latest(
        self, project_id: str, kind: OperationKind
    ) -> ProjectOperation | None: ...
    def recover_incomplete(self) -> list[ProjectOperation]: ...
