#pragma once
#include "xref_area_controls.h"
#include "direct_query_kernel.h"
#include <ostream>

namespace ga::xref {
// Bounded experiment: local native containment plus Autodesk world NURB edges.
// No polygon export, no fit points generated by this code, no source mutation.
void inspectAffineQueries(AcDbEntity& entity,const AcDbObjectIdArray& parents,
                          const AcGeMatrix3d& transform,
                          const std::vector<AreaControl>& controls,std::ostream& out);
}
