"""Independently compare retained source entities, DXF roundtrip and reader output."""
from collections import Counter
import hashlib
import json
from pathlib import Path
import sys
import time

import ezdxf
from ezdxf.lldxf.tagwriter import TagCollector
from shapely.geometry import LineString, shape

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT/'apps/api'))
from app.dxf_import.adapters import EzdxfReader
from app.geometry.geojson_size import coordinate_count

LAB = ROOT / '.runtime/cad-roi-20260916'
APPID = 'GREEN_ATLAS_LAB_SOURCE'


def geometry_tags(entity, version):
    """CAD serializer normalizes omitted defaults. Resource handles remap on clone."""
    result = []
    in_lab = False
    collector = TagCollector(dxfversion=version, optional=False)
    entity.export_dxf(collector)
    for code, value in collector.tags:
        if code == 1001:
            in_lab = value == APPID
        if in_lab:
            continue
        # Handle/owner/resource pointers require separate graph validation, not
        # value equality across documents with newly allocated handles.
        if code in (5, 105, 1005) or 320 <= code <= 369 or 390 <= code <= 399:
            continue
        # REGION group 2 is the modeler UID, regenerated by ezdxf on cloning.
        # ACIS geometry is independently compared byte-for-byte below.
        if entity.dxftype() == 'REGION' and code == 2:
            continue
        result.append((code, str(value)))
    return result


def main():
    began = time.monotonic()
    output = LAB/(sys.argv[1] if len(sys.argv) > 1 else 'verification.json')
    assert not output.exists()
    source = ezdxf.readfile(ROOT/'.runtime/cad-extended-20260916/full-root.dxf')
    fragment = LAB/'large-block-roi-100m.dxf'
    target = ezdxf.readfile(fragment)
    extraction = json.loads((LAB/'extraction.json').read_text())
    expected = json.loads((LAB/'expected-entities.json').read_text())
    mapping = {}
    mismatches = []
    acis = []
    for entity in target.modelspace():
        old_handle = entity.get_xdata(APPID)[0].value
        original = source.entitydb[old_handle]
        mapping[entity.dxf.handle] = old_handle
        left = geometry_tags(original, source.dxfversion)
        right = geometry_tags(entity, target.dxfversion)
        if left != right:
            mismatches.append(dict(source_handle=old_handle, type=original.dxftype(),
                                   source_tags=left, output_tags=right))
        if hasattr(original, 'sab'):
            acis.append(dict(source_handle=old_handle, output_handle=entity.dxf.handle,
                             payload_bytes=len(entity.sab), payload_equal=original.sab==entity.sab,
                             source_uid=original.dxf.get('uid'), output_uid=entity.dxf.get('uid'),
                             sha256=hashlib.sha256(entity.sab).hexdigest()))
    imported = EzdxfReader().read(fragment.name, fragment.read_bytes())
    features = imported.geometry.feature_collection['features']
    features_by_handle = {}
    for feature in features:
        features_by_handle.setdefault(feature['properties'].get('source_handle'), []).append(feature)
    missing = []
    bad_lines = []
    max_line_error = 0.0
    for entity in target.modelspace():
        handle = entity.dxf.handle
        fs = features_by_handle.get(handle, [])
        if not fs:
            missing.append(dict(source_handle=mapping[handle], output_handle=handle,
                                type=entity.dxftype(), layer=entity.dxf.layer))
        if entity.dxftype() == 'LINE' and fs:
            original = source.entitydb[mapping[handle]]
            geometry = LineString([(original.dxf.start.x, original.dxf.start.y),
                                   (original.dxf.end.x, original.dxf.end.y)])
            errors = [geometry.hausdorff_distance(shape(f['geometry'])) for f in fs]
            error = min(errors)
            max_line_error = max(max_line_error, error)
            if error > 1e-6:
                bad_lines.append(dict(source_handle=mapping[handle], error=error))
    result = dict(scope='large-block fragment only; no full project or normative acceptance',
                  retained_entities=len(mapping), expected_entities=len(expected),
                  source_handle_set_equal=set(mapping.values())==set(expected),
                  dxf_geometry_tag_mismatches=len(mismatches),
                  tag_mismatch_examples=mismatches[:5],
                  tag_comparison_excludes='ownership/resource handles, regenerated REGION UID and laboratory provenance XDATA; optional defaults normalized',
                  acis_payloads=acis, normalized_features=len(features),
                  normalized_coordinates=sum(coordinate_count(f['geometry']) for f in features),
                  normalized_missing=missing, max_line_hausdorff_error_m=max_line_error,
                  line_geometry_failures=bad_lines, warnings=imported.warnings,
                  source_layers=[layer.model_dump(mode='json') for layer in imported.layers],
                  extraction_preservation_passed=not mismatches and all(r['payload_equal'] for r in acis)
                       and set(mapping.values())==set(expected),
                  all_selected_entities_normalized=not missing,
                  first_probe_failure='5242 explicit elevation=0 attributes omitted on DXF write; compare tags with optional defaults suppressed',
                  seconds=time.monotonic()-began)
    with output.open('x') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    print(json.dumps({k:v for k,v in result.items() if k not in ('source_layers','tag_mismatch_examples')},ensure_ascii=False),flush=True)
    assert result['extraction_preservation_passed'] and not bad_lines


if __name__ == '__main__':
    main()
